---
dbt_poc:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ./.duckdb/dbt_poc.duckdb
      threads: 4
    test:
      type: duckdb
      path: ./.duckdb/dbt_poc_test.duckdb
      threads: 4
    prod:
      type: duckdb
      path: ./.duckdb/dbt_poc_prod.duckdb
      threads: 8
